app = "pipelines-api-staging"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[env]
  SERVER_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 250

[[vm]]
  cpu_kind = "performance"
  cpus = 2
  memory_mb = 4096
