name: Deploy Fly Restreamers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy_batch:
    name: Deploy Batch of Restreamers to Fly.io
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Parse Inputs and Deploy in Loop
        env:
          APP_NAMES_STR: ${{ vars.RESTREAMER_APP_NAMES }}
          SOURCE_URLS_STR: ${{ vars.RESTREAMER_SOURCE_URLS }}
          RTMP_TARGETS_LP_STR: ${{ vars.RESTREAMER_RTMP_TARGETS_LP }}
          RTMP_TARGETS_AI_STR: ${{ vars.RESTREAMER_RTMP_TARGETS_AI }}
          YOUTUBE_COOKIES_BASE64: ${{ secrets.YOUTUBE_COOKIES_BASE64 }}
          FLY_ORG: livepeer-673
          FLY_REGION: fra
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          IFS=',' read -r -a APP_NAME_ARRAY <<< "$APP_NAMES_STR"
          IFS=',' read -r -a SOURCE_URL_ARRAY <<< "$SOURCE_URLS_STR"
          IFS=',' read -r -a RTMP_TARGETS_LP_ARRAY <<< "$RTMP_TARGETS_LP_STR"
          IFS=',' read -r -a RTMP_TARGETS_AI_ARRAY <<< "$RTMP_TARGETS_AI_STR"

          num_app_names=${#APP_NAME_ARRAY[@]}
          if [[ $num_app_names -ne ${#SOURCE_URL_ARRAY[@]} || \
                $num_app_names -ne ${#RTMP_TARGETS_LP_ARRAY[@]} || \
                $num_app_names -ne ${#RTMP_TARGETS_AI_ARRAY[@]} ]]; then
            echo "Error: Input CSV lists have mismatched lengths. Ensure all lists (including app_names_csv) have the same number of items."
            exit 1
          fi

          if [[ $num_app_names -eq 0 || -z "${APP_NAME_ARRAY[0]}" ]]; then
            echo "No configurations (app names) found to deploy."
            exit 0
          fi

          echo "Found $num_app_names configurations to process."

          cd apps/restreamers

          for i in "${!APP_NAME_ARRAY[@]}"; do
            CURRENT_APP_NAME="${APP_NAME_ARRAY[$i]}"
            CURRENT_SOURCE_URL="${SOURCE_URL_ARRAY[$i]}"
            CURRENT_RTMP_TARGET_LP="${RTMP_TARGETS_LP_ARRAY[$i]}"
            CURRENT_RTMP_TARGET_AI="${RTMP_TARGETS_AI_ARRAY[$i]}"

            # Validate current app name (basic check, Fly will do the final validation)
            if [[ -z "$CURRENT_APP_NAME" ]]; then
              echo "Error: App name for configuration #$((i+1)) is empty. Skipping."
              continue
            fi

            echo ""
            echo "---------------------------------------------------------------------"
            echo "Processing configuration #$((i+1)) for App: $CURRENT_APP_NAME"
            echo "Source URL: $CURRENT_SOURCE_URL"
            echo "---------------------------------------------------------------------"

            echo "::group::Deploying app: $CURRENT_APP_NAME"

            echo "Checking if app '$CURRENT_APP_NAME' exists or creating it..."
            
            if ! flyctl status -a "$CURRENT_APP_NAME" >/dev/null 2>&1; then
              echo "App '$CURRENT_APP_NAME' does not exist. Creating..."
              flyctl apps create "$CURRENT_APP_NAME" --org "$FLY_ORG" --machines || {
                echo "Warning: Failed to create app '$CURRENT_APP_NAME'. It might already exist."
                # Verify the app exists now
                if ! flyctl status -a "$CURRENT_APP_NAME" >/dev/null 2>&1; then
                  echo "Error: App '$CURRENT_APP_NAME' still does not exist after creation attempt."
                  continue
                fi
              }
            else
              echo "App '$CURRENT_APP_NAME' already exists."
            fi

            echo "Setting secrets for app '$CURRENT_APP_NAME'..."
            # Updated secret names to reflect the new SOURCE_URL naming
            flyctl secrets set -a "$CURRENT_APP_NAME" --stage \
              YOUTUBE_URL_STREAM1="$CURRENT_SOURCE_URL" \
              RTMP_TARGET_LP="$CURRENT_RTMP_TARGET_LP" \
              RTMP_TARGET_AI="$CURRENT_RTMP_TARGET_AI" \
              YOUTUBE_COOKIES_BASE64="$YOUTUBE_COOKIES_BASE64" \
              PYTHONUNBUFFERED="1"

            echo "Deploying app '$CURRENT_APP_NAME' to region '$FLY_REGION'..."
            # Deploy from the restreamers directory where fly.toml is located
            flyctl deploy -a "$CURRENT_APP_NAME" --regions "$FLY_REGION" --ha=false --strategy immediate --config fly.toml --dockerfile Dockerfile

            echo "::endgroup::"
            # Optional: sleep 5 

          done
          echo "All $num_app_names configurations processed."
