name: Deploy Fishtank

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/fishtank/**"

jobs:
  deploy:
    name: Deploy Fishtank
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd apps/fishtank
          flyctl deploy --ha=false
