name: E2E Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install Playwright Browsers and Dependencies
        run: pnpm --filter app-e2e exec playwright install --with-deps chrome

      - name: Run Playwright tests
        id: playwright
        # TODO: sync, or at least lint env vars
        env:
          NEXT_PUBLIC_ENV: ${{ secrets.NEXT_PUBLIC_ENV }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_WEBHOOK_SECRET: ${{ secrets.CLERK_WEBHOOK_SECRET }}
          RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
          RESEND_FROM: ${{ secrets.RESEND_FROM }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}
          BETTERSTACK_URL: ${{ secrets.BETTERSTACK_URL }}
          FLAGS_SECRET: ${{ secrets.FLAGS_SECRET }}
          ARCJET_KEY: ${{ secrets.ARCJET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          STREAM_STATUS_ENDPOINT_URL: ${{ secrets.STREAM_STATUS_ENDPOINT_URL }}
          STREAM_STATUS_ENDPOINT_USER: ${{ secrets.STREAM_STATUS_ENDPOINT_USER }}
          STREAM_STATUS_ENDPOINT_PASSWORD: ${{ secrets.STREAM_STATUS_ENDPOINT_PASSWORD }}
          STREAM_STATUS_ENDPOINT_URL_SECONDARY: ${{ secrets.STREAM_STATUS_ENDPOINT_URL_SECONDARY }}
          MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
          LIVEPEER_STUDIO_API_KEY: ${{ secrets.LIVEPEER_STUDIO_API_KEY }}
          LIVEPEER_STUDIO_API_URL: ${{ secrets.LIVEPEER_STUDIO_API_URL }}
          LIVEPEER_STUDIO_RTMP_URL: ${{ secrets.LIVEPEER_STUDIO_RTMP_URL }}
          USERNAME_PASSWORD: ${{ secrets.USERNAME_PASSWORD }}
          KAFKA_BOOTSTRAP_NODE: ${{ secrets.KAFKA_BOOTSTRAP_NODE }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
          KAFKA_USER: ${{ secrets.KAFKA_USER }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          NEXT_PUBLIC_WEB_URL: ${{ secrets.NEXT_PUBLIC_WEB_URL }}
          NEXT_PUBLIC_DOCS_URL: ${{ secrets.NEXT_PUBLIC_DOCS_URL }}
          NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL: ${{ secrets.NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL }}
          NEXT_PUBLIC_AI_WEBRTC_BASE_URL: ${{ secrets.NEXT_PUBLIC_AI_WEBRTC_BASE_URL }}
          NEXT_PUBLIC_WHIP_URL: ${{ secrets.NEXT_PUBLIC_WHIP_URL }}
          NEXT_PUBLIC_WHIP_URL_SECONDARY: ${{ secrets.NEXT_PUBLIC_WHIP_URL_SECONDARY }}
          NEXT_PUBLIC_RTMP_URL: ${{ secrets.NEXT_PUBLIC_RTMP_URL }}
          NEXT_PUBLIC_RTMP_URL_SECONDARY: ${{ secrets.NEXT_PUBLIC_RTMP_URL_SECONDARY }}
          NEXT_PUBLIC_AI_GATEWAY_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_AI_GATEWAY_API_BASE_URL }}
          NEXT_PUBLIC_AI_GATEWAY_API_BASE_URL_SECONDARY: ${{ secrets.NEXT_PUBLIC_AI_GATEWAY_API_BASE_URL_SECONDARY }}
          NEXT_PUBLIC_LIVEPEER_STUDIO_API_KEY: ${{ secrets.NEXT_PUBLIC_LIVEPEER_STUDIO_API_KEY }}
          NEXT_PUBLIC_LIVEPEER_STUDIO_API_URL: ${{ secrets.NEXT_PUBLIC_LIVEPEER_STUDIO_API_URL }}
          NEXT_PUBLIC_INTERCOM_APP_ID: ${{ secrets.NEXT_PUBLIC_INTERCOM_APP_ID }}
          NEXT_PUBLIC_SITE_PASSWORD: ${{ secrets.NEXT_PUBLIC_SITE_PASSWORD }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_HUBSPOT_PORTAL_ID: ${{ secrets.NEXT_PUBLIC_HUBSPOT_PORTAL_ID }}
          NEXT_PUBLIC_HUBSPOT_FORM_ID: ${{ secrets.NEXT_PUBLIC_HUBSPOT_FORM_ID }}
        run: pnpm --filter app-e2e test:dev
        continue-on-error: true

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: apps/app-e2e/screenshots/

      - name: Fail workflow if tests failed
        if: steps.playwright.outcome == 'failure'
        run: exit 1
