name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
  schedule:
    - cron: "*/30 * * * *"
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: production
            deployment_target: "Production - e2e"
          - env: staging
            deployment_target: "Staging - e2e"
          - env: preview
            deployment_target: "Preview - e2e"

    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == matrix.env) ||
      (github.event_name == 'pull_request' && matrix.env == 'preview') ||
      (github.event_name == 'push' && matrix.env == 'preview')

    environment: ${{ matrix.deployment_target }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Vercel deployment to be ready
        if: matrix.env == 'preview'
        run: sleep 150

      - name: Capture Vercel Preview URL
        if: matrix.env == 'preview'
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}

      - name: Set TEST_APP_URL from preview URL
        if: matrix.env == 'preview'
        run: echo "TEST_APP_URL=https://${{ steps.vercel_preview_url.outputs.preview_url }}" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter app-e2e...

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install Playwright Browsers and Dependencies
        run: pnpm --filter app-e2e exec playwright install --with-deps chrome

      - name: Run Playwright tests for ${{ matrix.env }}
        id: playwright
        env:
          TEST_APP_URL: ${{ env.TEST_APP_URL }}
        run: pnpm --filter app-e2e test:prod
        continue-on-error: true

      - name: Upload test screenshots for ${{ matrix.env }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.env }}
          path: apps/app-e2e/screenshots/
          retention-days: 14

      - name: Fail workflow if tests failed for ${{ matrix.env }}
        if: steps.playwright.outcome == 'failure'
        run: |
          echo "::error::Playwright tests failed for the ${{ matrix.env }} environment."
          exit 1
